version: 0.0.{build}
image: Visual Studio 2015
only_commits:
  message: /build/                # Start a new build if message contains 'build'
platform:
- x86
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
    boost_dir: C:\Libraries\boost_1_69_0\
    version_ : 0.0.14
  matrix:
#  - PYTHON: 27
  - PYTHON: 36
    init_command:  python setup.py sdist && pip install  --verbose dist\pydggrid-%version_%.tar.gz
    deploy_command:  pip install wheel && pip install twine && python setup.py sdist bdist_wheel &&  del .\dist\pydggrid-%version_%.tar.gz & python -m twine upload dist/* -u %pipy_username% -p %pipy_password%
  - PYTHON: 37
    init_command:  python setup.py sdist && pip install  --verbose dist\pydggrid-%version_%.tar.gz
    deploy_command:  pip install wheel && pip install twine && python setup.py sdist bdist_wheel && (if %PLATFORM%==x86 del .\dist\pydggrid-%version_%.tar.gz) & python -m twine upload dist/* -u %pipy_username% -p %pipy_password%
  - PYTHON: 35
    init_command:  python setup.py sdist && pip install  --verbose dist\pydggrid-%version_%.tar.gz
    deploy_command:  pip install wheel && pip install twine && python setup.py sdist bdist_wheel &&  del .\dist\pydggrid-%version_%.tar.gz & python -m twine upload dist/* -u %pipy_username% -p %pipy_password%

#  - CONDA: 27
  - CONDA: 36
    init_command: conda build conda.recipe && conda install --use-local pydggrid
    deploy_command:
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- ps: |
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64"   }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install -q conda-build
    }
build_script:
- cmd: '%init_command%'
test_script:
- cmd: python -m unittest discover
deploy_script:
- cmd: '%deploy_command%'