version: '{build}'
image: Visual Studio 2015
platform:
- x86
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
#  - PYTHON: 27
  - PYTHON: 36
#  - CONDA: 27
  - CONDA: 36
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- ps: |
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") {
      $env:PYTHON = "$env:PYTHON-x64"
      call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
      }else{
      call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

      }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install -q conda-build
    }
build_script:
- ps: |
    if ($env:PYTHON) {
      $env:boost_dir="C:\Libraries\boost_1_69_0\"
      python setup.py sdist
      pip install  --verbose dist\pydggrid-0.0.7.tar.gz
    } else {
      conda build conda.recipe
      conda install --use-local pydggrid
    }
test_script:
#- ps: python -m unittest discover
