version: 1.0.'{build}'
image: Visual Studio 2015
only_commits:
  message: /build/                # Start a new build if message contains 'build'
platform:
- x86
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
    boost_dir: C:\Libraries\boost_1_69_0\
  matrix:
#  - PYTHON: 27
  - PYTHON: 36
    init_command: python setup.py sdist && pip install  --verbose dist\pydggrid-0.0.7.tar.gz  && python setup.py sdist bdist_wheel && python -m twine upload dist/* -u %pipy_username% -p %pipy_password%

#  - CONDA: 27
  - CONDA: 36
    init_command: conda build conda.recipe && conda install --use-local pydggrid
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- cmd: pip install wheel
- ps: |
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64"   }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install -q conda-build
    }
build_script:
#- cmd: python setup.py sdist && pip install  --verbose dist\pydggrid-0.0.7.tar.gz && python setup.py sdist bdist_wheel && python -m twine upload dist/* -u %pipy_username% -p %pipy_password%
#- cmd: pip install  --verbose dist\pydggrid-0.0.7.tar.gz
#- cmd: python setup.py sdist bdist_wheel
#- cmd: python -m twine upload dist/* -u %pipy_username% -p %pipy_password%
#- cmd: am2222
#- cmd: %pipy_password%
#- cmd: IF "%env%"!="PYTHON" (call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86) ELSE (ECHO "probably a 64bit build")
- cmd: '%init_command%'

#- ps: |
#    if (!$env:PYTHON) {
#      $env:boost_dir="C:\Libraries\boost_1_69_0\"
#      python setup.py sdist
#      pip install  --verbose dist\pydggrid-0.0.7.tar.gz
#    } else {
#      conda build conda.recipe
#      conda install --use-local pydggrid
#    }
test_script:
- cmd: python -m unittest discover
