language: cpp
dist: Xenial
sudo: true
matrix:
  include:
  - os: linux
    env:
      - PYTHON=3.6
      - CXX=g++-5
      - CC=gcc-5
      - CXXFLAGS = "$CXXFLAGS -std=c++14"
#  - os: linux
#    env: CONDA=3.6 CXX=g++ CC=gcc CXXFLAGS = "$CXXFLAGS -std=c++14"
# Boost
addons:
  apt:
    update: true
    sources:
      - boost-latest
    packages:
      - libboost-all-dev
      - g++-5

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install gcc-5 -y
  - sudo apt-get install g++-5 -y
  - sudo apt-get install python-pip python-dev build-essential
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip
  - sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
  - sudo apt-get update
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal-dev
  - sudo apt-get install shapelib
  - sudo apt-get install libshp-dev
  - sudo pip install --user --upgrade pip virtualenv
  - sudo python3 -m pip install --upgrade pip
  - sudo python3 -m pip install pybind11




install:
#- |
#  if [ -n "$PYTHON" ]; then
#    sudo apt-get install -qq g++-6
#    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    - cd $TRAVIS_BUILD_DIR
    - ls $HOME
    - sudo python3 setup.py install
#    - sudo python3 setup.py sdist
#    - sudo pip install --verbose dist/*.tar.gz
#  elif [ -n "$CONDA" ]; then
#    conda build conda.recipe
#    conda install --use-local pydggrid
#  fi
script:
  - cd $TRAVIS_BUILD_DIR
  - sudo python3 -m unittest discover
