language: cpp
dist: Xenial
sudo: true
matrix:
  include:
  - os: linux
    env: PYTHON=3.6,CXXFLAGS = "$CXXFLAGS -std=c++14"
  - os: linux
    env: CONDA=3.6,CXXFLAGS = "$CXXFLAGS -std=c++14"
# Boost
addons:
  apt:
    packages: libboost-all-dev
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-5.4 CC=gcc-5.4 CXXFLAGS = "$CXXFLAGS -std=c++14";
  fi
  if [ -n "$PYTHON" ]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update; brew install python3;
    fi
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get update -qq
    pip install --user --upgrade pip virtualenv
    virtualenv -p python3 venv
    source venv/bin/activate
    pip install pybind11
  elif [ -n "$CONDA" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64;
    fi
    wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no
    conda config --add channels conda-forge
    conda update -q conda
    conda install -q conda-build
    conda create -q -n test-environment python=$CONDA
    source activate test-environment
  fi
install:
- |
  if [ -n "$PYTHON" ]; then
    sudo apt-get install -qq g++-6
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    python setup.py sdist
    pip install --verbose dist/*.tar.gz
  elif [ -n "$CONDA" ]; then
    conda build conda.recipe
    conda install --use-local pydggrid
  fi
script:
- python tests/test.py
